export const CATEGORY_ACTION_TYPES = {
    SET_CURRENT_CATEGORY: "SET_CURRENT_CATEGORY",
    FETCH_CATEGORY_START:"FETCH_CATEGORY_START",
    FETCH_CATEGORY_SUCCESS:"FETCH_CATEGORY_SUCCESS",
    FETCH_CATEGORY_FAILED:"FETCH_CATEGORY_FAILED"
}